### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by julianqp** [freenetdigital/prometheus_oracle_exporter#10]
When I try to run the ./prometheus_oracle_exporter-amd64 I get an index out of range problem that is given by:

panic: runtime error: index out of range

goroutine 13 [running]:
main.(*Exporter).ScrapeAlertlog(0xc420198100)
        /home/mneumann3/repo/prometheus_oracle_exporter/alertlog.go:117 +0xc4c
main.(*Exporter).Collect(0xc420198100, 0xc4200785a0)
        /home/mneumann3/repo/prometheus_oracle_exporter/main.go:875 +0x31c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:409 +0x5c
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:418 +0x4ac

**Comment by floyd871** [comment]
Please post your config, "oracle.conf"

**Comment by julianqp** [comment]
Hi, oracle.conf is configurated, but now it is giving this problem.

 ./oracle_exporter
INFO[0000] Starting Prometheus Oracle exporter 1.1.0     source="main.go:938"
INFO[0000] Config loaded:  oracle.conf                   source="main.go:940"
INFO[0000] Listening on :9161                            source="main.go:948"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x21f52e8 pc=0x7fc3b821e0d6]

runtime stack:
runtime.throw(0x8d9c65, 0x2a)
        /usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
        /usr/lib/go-1.10/src/runtime/signal_unix.go:372 +0x28e
....

How I could solved?

**Comment by floyd871** [comment]
Again, please post your config, "oracle.conf" and the full Error Stack.

**Comment by julianqp** [comment]
connections:
 - connection: ****/*****@localhost:puerto/A
   database: A
   instance: A
   alertlog:
    - file: /path/to/alert_A.log
      ignoreora:
       - ORA-00455
       - ORA-3127
       - ORA-0600
       - ORA-7445
       - ORA-600
       - ORA-07445
       - ORA-00001
       - ORA-01033
       - ORA-01041
       - ORA-01089
       - ORA-01555
       - ORA-28
       - ORA-235
       - ORA-609
       - ORA-3136
   queries:
    - sql: "SELECT 3 FROM dual"
      name: sample3
    - sql: "SELECT 4 FROM dual"
      name: sample4

**Comment by julianqp** [comment]
./oracle_exporter
INFO[0000] Starting Prometheus Oracle exporter 1.1.0     source="main.go:938"
INFO[0000] Config loaded:  oracle.conf                   source="main.go:940"
INFO[0000] Listening on :9161                            source="main.go:948"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2ca2078 pc=0x7fa0010450d6]

runtime stack:
runtime.throw(0x8d9c65, 0x2a)
        /usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
        /usr/lib/go-1.10/src/runtime/signal_unix.go:372 +0x28e

goroutine 18 [syscall]:
runtime.cgocall(0x7cd350, 0xc42003e6c0, 0x29)
        /usr/lib/go-1.10/src/runtime/cgocall.go:128 +0x64 fp=0xc42003e680 sp=0xc42003e648 pc=0x4045f4
github.com/mattn/go-oci8._Cfunc_OCIHandleFree(0x2ca2078, 0x4, 0x0)
        _cgo_gotypes.go:504 +0x4d fp=0xc42003e6c0 sp=0xc42003e680 pc=0x73297d
github.com/mattn/go-oci8.(*OCI8Stmt).Close.func1(0x2ca2078, 0xc400000004, 0x0)
        /home/mneumann3/go/src/github.com/mattn/go-oci8/oci8.go:942 +0x5e fp=0xc42003e6f8 sp=0xc42003e6c0 pc=0x73fd0e
github.com/mattn/go-oci8.(*OCI8Stmt).Close(0xc4203d5e00, 0x0, 0x0)
        /home/mneumann3/go/src/github.com/mattn/go-oci8/oci8.go:942 +0x6d fp=0xc42003e728 sp=0xc42003e6f8 pc=0x73758d
runtime.call32(0x0, 0x8e7790, 0xc4203dc000, 0x2000000020)
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:573 +0x3b fp=0xc42003e758 sp=0xc42003e728 pc=0x45643b
runtime.runfinq()
        /usr/lib/go-1.10/src/runtime/mfinal.go:222 +0x1eb fp=0xc42003e7e0 sp=0xc42003e758 pc=0x4186cb
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42003e7e8 sp=0xc42003e7e0 pc=0x458be1
created by runtime.createfing
        /usr/lib/go-1.10/src/runtime/mfinal.go:156 +0x62

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f9ffcd47ff0, 0x72, 0x0)
        /usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200d8718, 0x72, 0xc4200a6000, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200d8718, 0xffffffffffffff00, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4200d8700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc4200d8700, 0xc420162260, 0xc420065d28, 0x404118)
        /usr/lib/go-1.10/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc4200a2298, 0xc420065d58, 0x403077, 0xc420162260)
        /usr/lib/go-1.10/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc4200a2298, 0xc420065da0, 0xc420065da8, 0x18)
        /usr/lib/go-1.10/src/net/tcpsock.go:246 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4200a2298, 0x8e7ca0, 0xc4201621e0, 0x9232a0, 0xc4201695f0)
        /usr/lib/go-1.10/src/net/http/server.go:3216 +0x2f
net/http.(*Server).Serve(0xc420176270, 0x922b20, 0xc4200a2298, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/http/server.go:2770 +0x1a5
net/http.(*Server).ListenAndServe(0xc420176270, 0xc420176270, 0x2)
        /usr/lib/go-1.10/src/net/http/server.go:2711 +0xa9
net/http.ListenAndServe(0x8c8511, 0x5, 0x0, 0x0, 0x5, 0xc42009c2a0)
        /usr/lib/go-1.10/src/net/http/server.go:2969 +0x7a
main.main()
        /home/mneumann3/repo/prometheus_oracle_exporter/main.go:949 +0x2fa

goroutine 22 [runnable]:
runtime.Gosched()
        /usr/lib/go-1.10/src/runtime/proc.go:263 +0x1e
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc4200a6540, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:464 +0x7b2
github.com/prometheus/client_golang/prometheus.UninstrumentedHandler.func1(0x9220a0, 0xc4200a2598, 0xc42021e200)
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/http.go:75 +0x47
net/http.HandlerFunc.ServeHTTP(0x8e78a8, 0x9220a0, 0xc4200a2598, 0xc42021e200)
        /usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
net/http.(Handler).ServeHTTP-fm(0x9220a0, 0xc4200a2598, 0xc42021e200)
        /usr/lib/go-1.10/src/net/http/h2_bundle.go:5475 +0x4d
github.com/prometheus/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0x922660, 0xc4203641c0, 0xc42021e200)
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/http.go:296 +0x229
net/http.HandlerFunc.ServeHTTP(0xc4201d7950, 0x922660, 0xc4203641c0, 0xc42021e200)
        /usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
main.(*Exporter).Handler(0xc4200f0300, 0x922660, 0xc4203641c0, 0xc42021e200)
        /home/mneumann3/repo/prometheus_oracle_exporter/main.go:933 +0x1cc
main.(*Exporter).Handler-fm(0x922660, 0xc4203641c0, 0xc42021e200)
        /home/mneumann3/repo/prometheus_oracle_exporter/main.go:944 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420178610, 0x922660, 0xc4203641c0, 0xc42021e200)
        /usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xd4b140, 0x922660, 0xc4203641c0, 0xc42021e200)
        /usr/lib/go-1.10/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc420176270, 0x922660, 0xc4203641c0, 0xc42021e200)
        /usr/lib/go-1.10/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4201621e0, 0x9231e0, 0xc4200a7080)
        /usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go-1.10/src/net/http/server.go:2795 +0x27b

goroutine 244 [IO wait]:
internal/poll.runtime_pollWait(0x7f9ffcd47f20, 0x72, 0xc42003ee58)
        /usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200d8798, 0x72, 0xffffffffffffff00, 0x91ee20, 0xd1cba0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200d8798, 0xc420169600, 0x1, 0x1)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200d8780, 0xc4201696f1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4200d8780, 0xc4201696f1, 0x1, 0x1, 0xc420072f60, 0x0, 0xc4200a7158)
        /usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200a22a8, 0xc4201696f1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc4201696e0)
        /usr/lib/go-1.10/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
        /usr/lib/go-1.10/src/net/http/server.go:664 +0xce

goroutine 12 [semacquire]:
sync.runtime_Semacquire(0xc420024c7c)
        /usr/lib/go-1.10/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420024c70)
        /usr/lib/go-1.10/src/sync/waitgroup.go:129 +0x72
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc420024c70, 0xc4204e4120)
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:423 +0x2b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:422 +0x4de

goroutine 13 [runnable]:
syscall.Syscall(0x0, 0x7, 0xc420254000, 0x200, 0x101, 0x200, 0x0)
        /usr/lib/go-1.10/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x7, 0xc420254000, 0x200, 0x200, 0xc420070101, 0x0, 0x0)
        /usr/lib/go-1.10/src/syscall/zsyscall_linux_amd64.go:749 +0x5f
syscall.Read(0x7, 0xc420254000, 0x200, 0x200, 0x0, 0xc420032558, 0xc420032500)
        /usr/lib/go-1.10/src/syscall/syscall_unix.go:162 +0x49
internal/poll.(*FD).Read(0xc4203bc140, 0xc420254000, 0x200, 0x200, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:153 +0x118
os.(*File).read(0xc42000e020, 0xc420254000, 0x200, 0x200, 0x46cab1, 0x81c9e0, 0x200)
        /usr/lib/go-1.10/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc42000e020, 0xc420254000, 0x200, 0x200, 0x200, 0x200, 0xc420254000)
        /usr/lib/go-1.10/src/os/file.go:107 +0x6a
bytes.(*Buffer).ReadFrom(0xc4203de070, 0x91e2e0, 0xc42000e020, 0xc4200a4f00, 0x0, 0xc42000e020)
        /usr/lib/go-1.10/src/bytes/buffer.go:205 +0xa0
io/ioutil.readAll(0x91e2e0, 0xc42000e020, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/io/ioutil/ioutil.go:36 +0xb5
io/ioutil.ReadAll(0x91e2e0, 0xc42000e020, 0xc42000e020, 0x0, 0x0, 0x1, 0xc4204b8070)
        /usr/lib/go-1.10/src/io/ioutil/ioutil.go:45 +0x3e
github.com/prometheus/procfs.Proc.NewStat(0xfa9d, 0x8c84fd, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mneumann3/go/src/github.com/prometheus/procfs/proc_stat.go:100 +0x14a
github.com/prometheus/client_golang/prometheus.(*processCollector).processCollect(0xc4200a6580, 0xc4204e4120)
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/process_collector.go:123 +0xcc
github.com/prometheus/client_golang/prometheus.(*processCollector).(github.com/prometheus/client_golang/prometheus.processCollect)-fm(0xc4204e4120)
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/process_collector.go:89 +0x34
github.com/prometheus/client_golang/prometheus.(*processCollector).Collect(0xc4200a6580, 0xc4204e4120)
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/process_collector.go:107 +0x33
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:409 +0x5c
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:462 +0x7ad

goroutine 248 [runnable]:
context.WithCancel(0x923220, 0xc4200a0030, 0x20, 0x0, 0x0)
        /usr/lib/go-1.10/src/context/context.go:231 +0x3f
database/sql.OpenDB(0x921660, 0xc4203ee0c0, 0x921660)
        /usr/lib/go-1.10/src/database/sql/sql.go:624 +0x3d
database/sql.Open(0x8c838d, 0x4, 0xc42009c3c0, 0x22, 0x0, 0x2, 0x2)
        /usr/lib/go-1.10/src/database/sql/sql.go:673 +0x206
main.(*Exporter).Connect(0xc4200f0300)
        /home/mneumann3/repo/prometheus_oracle_exporter/main.go:776 +0x18c
main.(*Exporter).Collect(0xc4200f0300, 0xc4204e4120)
        /home/mneumann3/repo/prometheus_oracle_exporter/main.go:842 +0xa3
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:409 +0x5c
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:462 +0x7ad

**Comment by floyd871** [comment]
You are  using direct connection instead of TNSNAMES.ora. Many people seems to have problems with the exporter when using direct connection:

```
  ****/*****@localhost:puerto/A
```
So please, configure your connections via TNSNAMES.ora

TNSNAMES.ora:
```
A =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVICE_NAME = A)
    )
  )
```
```
 ****/*****@A
```

**Comment by gowri427** [comment]
Hi Team,

How can i display the results of "oracledb_query (Self defined Queries in Configuration File)" in Grafana??

For example i want to display the status of database backup from V$RMAN_BACKUP_JOB_DETAILS view.

select status from V$RMAN_BACKUP_JOB_DETAILS;

Please help me 

Thanks 
Gowri Reddi.
