### ISSUE TITLE
Hi Team,

### ISSUE THREAD

**Issue by gowri427** [freenetdigital/prometheus_oracle_exporter#11]
Hi Team,

How can i display the results of "oracledb_query (Self defined Queries in Configuration File)" in Grafana??

For example i want to display the status of database backup from V$RMAN_BACKUP_JOB_DETAILS view.

select status from V$RMAN_BACKUP_JOB_DETAILS;

Please help me 

Thanks 
Gowri Reddi.

_Originally posted by @gowri427 in https://github.com/freenetdigital/prometheus_oracle_exporter/issue_comments#issuecomment-451817912_

**Comment by floyd871** [comment]
Self defined queries need to return a numeric value. So in your case you have to to a workaround. Cast the expected vaules to a number:

select decode(status,'COMPLETED',1,0) from V$RMAN_BACKUP_JOB_DETAILS;

**Comment by gowri427** [comment]
Hi floyd871,

Thanks for you quick reply and it helps me a lot. 

And one more thing , i want to display "oracledb_error" output as table format as shown in below link
https://raw.githubusercontent.com/freenetdigital/prometheus_oracle_exporter/master/grafana/errors.png

Can you please share what steps you followed to create "oracle errors" dashboard ??

Regards
Gowri Reddi

**Comment by floyd871** [comment]
All Dashboards are in the Grafana Folder. 
https://github.com/freenetdigital/prometheus_oracle_exporter/blob/master/grafana/errors.json
