### ISSUE TITLE
add the explanation on hpow to launch the build process in the readme

### ISSUE THREAD

**Issue by Grummfy** [freenetdigital/prometheus_oracle_exporter#15]
Hello,
an explanation on  how to build this exporter would be great.

thanks

**Comment by floyd871** [comment]
- Install go
- clone this repo
- go tinstall
- go build

**Comment by Grummfy** [comment]
With `go tinstall`
> go tinstall: unknown command

I try with `go install` and see
> main.go:9:3: cannot find package "github.com/mattn/go-oci8" in any of:
> 	/usr/local/go/src/github.com/mattn/go-oci8 (from $GOROOT)
> 	/go/src/github.com/mattn/go-oci8 (from $GOPATH)
> main.go:10:5: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
> 	/usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
> 	/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
> alertlog.go:10:4: cannot find package "github.com/prometheus/common/log" in any of:
> 	/usr/local/go/src/github.com/prometheus/common/log (from $GOROOT)
> 	/go/src/github.com/prometheus/common/log (from $GOPATH)
> misc.go:8:5: cannot find package "gopkg.in/yaml.v2" in any of:
> 	/usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
> 	/go/src/gopkg.in/yaml.v2 (from $GOPATH)
>
