### ISSUE TITLE
about TS

### ISSUE THREAD

**Issue by Freel-Freel** [freenetdigital/prometheus_oracle_exporter#16]
We are have a metrics (name="SCHEMA_DEV4"):
`
oracledb_tablespace{autoextend="NO",contents="PERMANENT",database="uat",dbinstance="uat",instance="box99-07:9161",job="automatique",name="SCHEMA_DEV4",node="lhpm99-07",team="devops",type="free"}537902055424
oracledb_tablespace{autoextend="NO",contents="PERMANENT",database="uat",dbinstance="uat",instance="box99-07:9161",job="automatique",name="SCHEMA_DEV4",node="lhpm99-07",team="devops",type="total"}1064062418944
oracledb_tablespace{autoextend="NO",contents="PERMANENT",database="uat",dbinstance="uat",instance="box99-07:9161",job="automatique",name="SCHEMA_DEV4",node="lhpm99-07",team="devops",type="used"}526160363520
oracledb_tablespace{autoextend="YES",contents="PERMANENT",database="uat",dbinstance="uat",instance="box99-07:9161",job="automatique",name="SCHEMA_DEV4",node="lhpm99-07",team="devops",type="free"}537902055424
oracledb_tablespace{autoextend="YES",contents="PERMANENT",database="uat",dbinstance="uat",instance="box99-07:9161",job="automatique",name="SCHEMA_DEV4",node="lhpm99-07",team="devops",type="total"}343588847616
oracledb_tablespace{autoextend="YES",contents="PERMANENT",database="uat",dbinstance="uat",instance="box99-07:9161",job="automatique",name="SCHEMA_DEV4",node="lhpm99-07",team="devops",type="used"}-194313207808
`
But I got six metrics insted of three.

I sent query:

`
select * from dba_data_files where tablespace_name='SCHEMA_DEV4';
`

I got following answer:
`
FILE_ID | TABLESPACE_NAME | BYTES | BLOCKS | STATUS | RELATIVE_FNO | AUTOEXTENSIBLE | MAXBYTES | MAXBLOCKS | INCREMENT_BY | USER_BYTES | USER_BLOCKS | ONLINE_STATUS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
21 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 21 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
26 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 26 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
27 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 27 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
30 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 30 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
31 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 31 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
41 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 41 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
42 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 42 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
43 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 43 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
57 | SCHEMA_DEV4 | 32 212 254 720 | 3 932 160 | AVAILABLE | 57 | NO | 0 | 0 | 0 | 32211206144 | 3 932 032 | ONLINE
32 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 32 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
33 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 33 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
34 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 34 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
35 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 35 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
36 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 36 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
37 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 37 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
60 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 60 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
61 | SCHEMA_DEV4 | 34 358 689 792 | 4 194 176 | AVAILABLE | 61 | NO | 0 | 0 | 0 | 34357641216 | 4 194 048 | ONLINE
62 | SCHEMA_DEV4 | 17 179 869 184 | 2 097 152 | AVAILABLE | 62 | NO | 0 | 0 | 0 | 17178820608 | 2 097 024 | ONLINE
78 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 78 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
79 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 79 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
80 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 80 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
81 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 81 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
82 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 82 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
83 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 83 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
84 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 84 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
85 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 85 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
86 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 86 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
87 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 87 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
88 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 88 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
89 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 89 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
90 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 90 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
91 | SCHEMA_DEV4 | 33 285 996 544 | 4 063 232 | AVAILABLE | 91 | NO | 0 | 0 | 0 | 33284947968 | 4 063 104 | ONLINE
7 | SCHEMA_DEV4 | 34 359 721 984 | 4 194 302 | AVAILABLE | 7 | YES | 34 359 721 984 | 4 194 302 | 12 800 | 34358624256 | 4 194 168 | ONLINE
12 | SCHEMA_DEV4 | 34 359 721 984 | 4 194 302 | AVAILABLE | 12 | YES | 34 359 721 984 | 4 194 302 | 12 800 | 34358624256 | 4 194 168 | ONLINE
14 | SCHEMA_DEV4 | 34 351 349 760 | 4 193 280 | AVAILABLE | 14 | YES | 34 359 721 984 | 4 194 302 | 12 800 | 34350301184 | 4 193 152 | ONLINE
15 | SCHEMA_DEV4 | 34 359 721 984 | 4 194 302 | AVAILABLE | 15 | YES | 34 359 721 984 | 4 194 302 | 12 800 | 34358624256 | 4 194 168 | ONLINE
16 | SCHEMA_DEV4 | 34 359 721 984 | 4 194 302 | AVAILABLE | 16 | YES | 34 359 721 984 | 4 194 302 | 262 144 | 34358624256 | 4 194 168 | ONLINE
17 | SCHEMA_DEV4 | 34 359 721 984 | 4 194 302 | AVAILABLE | 17 | YES | 34 359 721 984 | 4 194 302 | 262 144 | 34358624256 | 4 194 168 | ONLINE
23 | SCHEMA_DEV4 | 34 359 721 984 | 4 194 302 | AVAILABLE | 23 | YES | 34 359 721 984 | 4 194 302 | 1 | 34358624256 | 4 194 168 | ONLINE
24 | SCHEMA_DEV4 | 34 359 721 984 | 4 194 302 | AVAILABLE | 24 | YES | 34 359 721 984 | 4 194 302 | 262 144 | 34358624256 | 4 194 168 | ONLINE
25 | SCHEMA_DEV4 | 34 359 721 984 | 4 194 302 | AVAILABLE | 25 | YES | 34 359 721 984 | 4 194 302 | 262 144 | 34358624256 | 4 194 168 | ONLINE
53 | SCHEMA_DEV4 | 34 359 721 984 | 4 194 302 | AVAILABLE | 53 | YES | 34 359 721 984 | 4 194 302 | 1 | 34358624256 | 4 194 168 | ONLINE
`
![default](https://user-images.githubusercontent.com/18048358/52561237-dab00f00-2e0b-11e9-9c27-c3b468478a1c.png)

Maybe we have created wrong TS ? Or where the problem is ?

**Comment by floyd871** [comment]
Strange, my exporter collects the ts data seperated by autoextend of the datafiles. This is the query:
```
   WITH
        getsize AS (SELECT tablespace_name, autoextensible, SUM(bytes) tsize
                           FROM dba_data_files GROUP BY tablespace_name, autoextensible),
        getfree as (SELECT tablespace_name, contents, SUM(blocks*block_size) tfree
                          FROM DBA_LMT_FREE_SPACE a, v$tablespace b, dba_tablespaces c
                          WHERE a.TABLESPACE_ID= b.ts# and b.name=c.tablespace_name
                          GROUP BY tablespace_name,contents)
    SELECT a.tablespace_name, b.contents, a.tsize,  b.tfree, a.autoextensible autoextend
    FROM GETSIZE a, GETFREE b
    WHERE a.tablespace_name = b.tablespace_name
    UNION
    SELECT tablespace_name, 'TEMPORARY', sum(tablespace_size), sum(free_space), 'NO'
    FROM dba_temp_free_space
    GROUP BY tablespace_name
```
I have to adapt that.

**Comment by gowri427** [comment]
Hi 
For tablespace total size ,i think we need to take query as SUM(MAXBYTES). Because, we allocated some space already to tablespace with autoextend ON.

**Comment by floyd871** [comment]
I think i fixed the Problem:

https://github.com/freenetdigital/prometheus_oracle_exporter/releases/tag/1.1.2

**Comment by Freel-Freel** [comment]
Thanks for the help.
Update the exporter and check.
