### ISSUE TITLE
Table space  Metrics showing -ve values

### ISSUE THREAD

**Issue by gowri427** [freenetdigital/prometheus_oracle_exporter#17]
Hi 
I am getting table space used values in negative number. 

oracledb_tablespace{autoextend="NO",contents="UNDO",database="XXXX",dbinstance="XXXX",exporter_id="freenetdigital",instance="XXXX",job="oracle_health",name="UNDOTBS1",type="used"} | -33856094208
-- | --

oracledb_tablespace{autoextend="YES",,contents="UNDO",database="XXXX",dbinstance="XXXX",exporter_id="freenetdigital",instance="XXXX",job="oracle_health",name="UNDOTBS1",type="used"} | -570114048
-- | --

Can you please check it asap.

**Comment by floyd871** [comment]
Do you have multiple datafiles for your TS and all have different setting for autoextenend ?

**Comment by gowri427** [comment]
Hi Team,
Yes , We have multiple datafiles for TS and for some datafiles autoextend is ON and for some it is OFF.

**Comment by floyd871** [comment]
I think i fixed this problem:

https://github.com/freenetdigital/prometheus_oracle_exporter/releases/tag/1.1.2
