### ISSUE TITLE
Having hard time to start the service 

### ISSUE THREAD

**Issue by skm2019** [freenetdigital/prometheus_oracle_exporter#19]
I have followed all the instructions but unable to start the service getting below error please help:

[oracle@localhost prometheus_oracle_exporter-master]$ ./prometheus_oracle_exporter-amd64 --configfile=/u01/userhome/oracle/scripts/prometheus_oracle_exporter-master/oracle.conf --web.listen-address :9161
INFO[0000] Starting Prometheus Oracle exporter 1.1.1     source="main.go:940"
FATA[0000] error: yaml: unmarshal errors:
  line 45: cannot unmarshal !!map into string  source="misc.go:72"

I am using go version 1.9 on oel7 linux

go version go1.9.2 linux/amd64

**Comment by floyd871** [comment]
The exporter could not read the configuration file. You have some "ident" errors. Check the sample file,
