### ISSUE TITLE
oracledb_query (Self defined Queries in Configuration File) not running

### ISSUE THREAD

**Issue by renuraj18** [freenetdigital/prometheus_oracle_exporter#20]
config file:
connections:
 - connection: **/***@tnsname
   database: ***
   instance: ***
   alertlog:
    - file: alert.log
      ignoreora:
       - ORA-00001
       - ORA-01033
       - ORA-01041

   queries:
    - sql: "select count(*) from dbo.AUDITTRAIL"
      name: sa03

with above config i am not able to get any query output
can you please help

**Comment by floyd871** [comment]
I've just check it i see the Metric:

```
queries:
    - sql: "select count(*) from sys.GV_$SESSION"
      name: sa03
```

```
oracledb_query{name="sa03"}  167
```
