### ISSUE TITLE
prometheus_oracle_exporter  Abnormal exit ！

### ISSUE THREAD

**Issue by xiaohaozifeifeifei** [freenetdigital/prometheus_oracle_exporter#25]
time="2019-07-04T14:13:49+08:00" level=info msg="Starting Prometheus Oracle exporter 1.1.1" source="main.go:940"
time="2019-07-04T14:13:49+08:00" level=info msg="Config loaded:  /u01/exporter/oracle.conf" source="main.go:942"
time="2019-07-04T14:13:49+08:00" level=info msg="Listening on :9161" source="main.go:950"
panic: label value "\xd3û\xa7\xc7\xeb\xc7\xf3ȡ\xcf\xfb\xb5\xb1ǰ\xb5Ĳ\xd9\xd7\xf7" is not valid UTF-8

goroutine 19 [running]:
github.com/prometheus/client_golang/prometheus.(*GaugeVec).WithLabelValues(0xc42000e220, 0xc420606320, 0x5, 0x5, 0xc4200ce7e0, 0x68)
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/gauge.go:217 +0x91
main.(*Exporter).ScrapeAlertlog(0xc42002e100)
        /home/mneumann3/go/src/github.com/freenetgigital/prometheus_oracle_exporter/alertlog.go:138 +0x8b9
main.(*Exporter).Collect(0xc42002e100, 0xc4200d0ea0)
        /home/mneumann3/go/src/github.com/freenetgigital/prometheus_oracle_exporter/main.go:877 +0x31c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x199
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:526 +0xe90

**Comment by floyd871** [comment]
Seems like an error i the config file. Can you attach it?
