### ISSUE TITLE
Don't find oracle exporter binary on usr/local/bin/

### ISSUE THREAD

**Issue by Seth1u** [freenetdigital/prometheus_oracle_exporter#27]
Hello ! 
I don't find oracle exporter binary on usr/local/bin/ when i unzip source code of exporter.

And how to configure service for this exporter ?

**Comment by floyd871** [comment]
Binaries are under https://github.com/freenetdigital/prometheus_oracle_exporter/releases
There is no automatic installation. Read the docs: https://github.com/freenetdigital/prometheus_oracle_exporter/blob/master/README.md

**Comment by Seth1u** [comment]
I have unzip it in directory : 
root@lab# pwd 
/opt/prometheus_oracle_exporter

And 
-rw-rw-r--. 1 supervision prometheus     4390 May  6 16:23 alertlog.go
drwxrwxr-x. 1 supervision prometheus      274 May  6 16:23 grafana
-rw-rw-r--. 1 root        root           1077 May  6 16:23 LICENSE
-rw-rw-r--. 1 monito prometheus    30519 May  6 16:23 main.go
-rw-rw-r--. 1 monito prometheus     2401 May  6 16:23 misc.go
-rw-r--r--. 1 monito prometheus 14103656 Jul 12 15:19 prometheus_oracle_exporter-amd64
-rw-rw-r--. 1 monito prometheus     4685 May  6 16:23 README.md

I want to start service of this exporter automatically with systemd service.
My config lokk like this  


[Unit]
Description=Prometheus ORACLE Exporter
After=network.target
User=supervision
Group=prometheus


[client]
user=sypervision
password=Suporacle

[Service]
Type=simple
Restart=always

[Service]

Environment=DATA_SOURCE_NAME=user/passwd@dbSID
Environment=ORACLE_SID=sdbSID
Environment=ORACLE_BASE=/oracle
Environment=ORACLE_HOME=/oracle/product/12.1.0.2
User=oracle
group=oinstall
Environment=LD_LIBRARY_PATH=/oracle/product/12.1.0.2/lib

ExecStart=/opt/prometheus_oracle_exporter/prometheus_oracle_exporter-amd64 -indexbytes -lobbytes -tablebytes -tablerows --configfile=/etc/.oracle_exporter.conf  --web.listen-address=0.0.0.0:9161

[Install]
WantedBy=multi-user.target

and finish with my oracle_exporter.conf 

connections:
 - connection: user/passwd@dbSID
   database: dbSID
   instance: dbSID
   alertlog:
    - file: /oracle/diag/rdbms/dbSIDtrace/alert_dbSID.log
      ignoreora:
       - ORA-00001
       - ORA-01033
       - ORA-01041
       - ORA-01089
       - ORA-01555
       - ORA-28
       - ORA-235
       - ORA-609
       - ORA-3136
   queries:
    - sql: "select 1 from dual"
      name: sample1
    - sql: "select 2 from dual"
      name: sample2

**Comment by Seth1u** [comment]
But after set this parameter on my server nothing metrics push on my prmometheus server.

**Comment by floyd871** [comment]
Prometheus pulls data from the exporters.

First, check with a curl if your exporter is working, then create a propper scrape config in Prometheus.

**Comment by Seth1u** [comment]
Thanks Michael Neumann ! 

I have already check with a curl and i have all metrics print. but on my prometheus serveur, i have got error 
Get http://localhost:9161/metrics: dial tcp my_serveur_IP:9161: connect: no route to host

**Comment by Seth1u** [comment]
And this one after run . /usr/local/bin/prometheus_oracle_exporter-amd64 --configfile=/opt/prometheus_oracle_exporter/oracle.conf  --web.listen-address=0.0.0.0:9161

panic: OCIEnvCreate error

goroutine 1 [running]:
github.com/mattn/go-oci8.init.0()
        /home/mneumann3/go/src/github.com/mattn/go-oci8/globals.go:165 +0x517

**Comment by Seth1u** [comment]
Thanks ! It works now !
