### ISSUE TITLE
How can I disable the alertlog feature?

### ISSUE THREAD

**Issue by fgprodigal** [freenetdigital/prometheus_oracle_exporter#28]
Cause I'm running the exporter on a specific server monitoring all oracle database, I can't reach the alert log from the server, so I want to disable this feature by deleting the alertlog field in the config, but the exporter can't startup if I do so.

**Comment by floyd871** [comment]
Yes you are right. In the latest commit i fixed that.
If you are using the binary you can help yourself in just adding any existing file in the config.
