### ISSUE TITLE
Missing metrics on oracle-short

### ISSUE THREAD

**Issue by changmao01** [freenetdigital/prometheus_oracle_exporter#29]
I have setup oracle_export 1.1.1 on Centos 6.9 64bit with Oracle 11.2.0.4.0. 
I can set oracle-short UP (with blue) in prometheus target. However, I run below commands without data return:
curl -s http://localhost:9161/metrics|grep oracledb_uptime
curl -s http://localhost:9161/metrics|grep oracledb_session

Starting command is as below:
/usr/local/bin/oracle_exporter -configfile "/home/appuser/oracle.conf"
INFO[0000] Starting Prometheus Oracle exporter 1.1.1     source="main.go:940"
INFO[0000] Config loaded:  /home/appuser/oracle.conf     source="main.go:942"
INFO[0000] Listening on :9161                            source="main.go:950"

Content of the configfile(/home/appuser/oracle.conf) is as below:
connections:
 - connection: <ogg>/<xxx>@<wsctest>
   database: WSCTEST
   instance: wsctest
   alertlog:
    - file: /home/wang/app/oracle/diag/rdbms/wsctest/wsctest/trace/alert_wsctest.log
      ignoreora:
       - ORA-00001
       - ORA-01033
       - ORA-01041
       - ORA-01089
       - ORA-01555
       - ORA-28
       - ORA-235
       - ORA-609
       - ORA-3136
   queries:
    - sql: "select 1 from dual"
      name: sample1
    - sql: "select 2 from dual"
      name: sample2

**Comment by Seth1u** [comment]
Hello changmao01 ! 
With wich user do you connect to your instance or your database ? 

In your oracle.conf, you must add your monitoring user and it password.

Exemple : 
connections:

connection: user/password@wsctest
database: WSCTEST
instance: wsctest
alertlog:
file: /home/wang/app/oracle/diag/rdbms/wsctest/wsctest/trace/alert_wsctest.log
ignoreora:
ORA-00001
ORA-01033
ORA-01041
ORA-01089
ORA-01555
ORA-28
ORA-235
ORA-609
ORA-3136
queries:
sql: "select 1 from dual"
name: sample1
sql: "select 2 from dual"
name: sample2


#################
Before do it, create your user and password on your database and add grant select for all views and data that you want to collect on database.

**Comment by floyd871** [comment]
After you do the curl command, do you see any error messages , like:

` ERRO[0010] Error connecting to database: ORA-12154: TNS:could not resolve the connect identifier specified  source="main.go:790"`

If not, show the output of the curl command without grep!

**Comment by changmao01** [comment]
@Seth1u , I have created one oracle database account for oracle export and grant some privileges to that account.

**Comment by changmao01** [comment]
@floyd871 , I did not see ORA- errors after running curl command. Below are some abstracts:
curl -s http://localhost:9161/metrics|grep -v '^#'
go_gc_duration_seconds{quantile="0"} 6.5023e-05
go_gc_duration_seconds{quantile="0.25"} 7.3382e-05
go_gc_duration_seconds{quantile="0.5"} 7.4265e-05
....
go_threads 16
oracledb_error_unix_seconds{database="WSCTEST",dbinstance="wsctest"} 1.563732e+09
oracledb_exporter_last_scrape_duration_seconds 0.010519231
oracledb_exporter_last_scrape_error 0
oracledb_exporter_scrapes_total 6
oracledb_up{database="WSCTEST",dbinstance="wsctest"} 0
process_cpu_seconds_total 0.14
process_max_fds 65535
process_open_fds 17
process_resident_memory_bytes 3.2612352e+07
process_start_time_seconds 1.56375869435e+09
process_virtual_memory_bytes 8.74799104e+08
process_virtual_memory_max_bytes -1
promhttp_metric_handler_requests_in_flight 1
promhttp_metric_handler_requests_total{code="200"} 5
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
[appuser@scsp00395 ~]$ curl -s http://localhost:9161/metrics|grep -v '^#'|wc
     50     100    2000

Below are some environments:
[appuser@scsp00395 ~]$ env|grep ORACLE
ORACLE_SID=wsctest
ORACLE_HOME=/home/wang/app/oracle/product/11.2.0/db_1

**Comment by changmao01** [comment]
@Seth1u ,

Just now I read your comments again, and got the answer. 
There're something wrong in my oracle.com as below:
<usser>/<password>@<tnsname>
It should be replaced as:
user/password@tnsname

**Replace the symbol "<" and ">".**

**Comment by floyd871** [comment]
Delete the file access.conf. Then the exporter scrapes the whole alertlog-file. Did you have ORA-xxxx in your alertlog file at all?

**Comment by Seth1u** [comment]
Hello it work now. thanks!

But when i define in oracle.conf 

ORA-00001
ORA-01033
ORA-01041
ORA-01089
ORA-01555
ORA-28 

i don't found it in oracledb_error{dbinstance=~'$dbinstance',ignore="1"}

**Comment by floyd871** [comment]
Did you see them when you omit ignore="1" ?
If yes. Please give me a part of your alertlogfile. From one date to another with an ORA-XXX within.
Maybe something is wrong withe my parsing.....
