### ISSUE TITLE
Oracle Errors doesn't work  

### ISSUE THREAD

**Issue by Seth1u** [freenetdigital/prometheus_oracle_exporter#30]

**Comment by Seth1u** [comment]
Hello! 
I added the errors in the oracle.conf file but on the dashboard no instances are displayed and the oracledb_error metrics are not displayed as well.

Thanks

**Comment by changmao01** [comment]
@Seth1u , what's the content of your oracle.conf? please try to run below  command to check oracle_exporter metrics:
curl -s http://localhost:9161/metrics|grep -v '^#'

**Comment by Seth1u** [comment]
oracledb_error_unix_seconds{database="test",dbinstance="test"} 1.563847239e+09
oracledb_exporter_last_scrape_duration_seconds 0.076459284
oracledb_exporter_last_scrape_error 0
oracledb_exporter_scrapes_total 3978


Nothing on grafana dashboard.

**Comment by floyd871** [comment]
Delete the file access.conf. Then the exporter scrapes the whole alertlog-file. Did you have ORA-xxxx in your  alertlog file at all?

**Comment by Seth1u** [comment]
Yes it work now. 
Thanks !!
I have another ask, can i create my own metrics like RMAN last backup, oracle version, oracle dataguard status, last Patch, materialized view, oracle locks ?

**Comment by floyd871** [comment]
Use the self defined queries for that.
