### ISSUE TITLE
Exporter don't work when i restart database 

### ISSUE THREAD

**Issue by Seth1u** [freenetdigital/prometheus_oracle_exporter#32]
Hello,

I tried to restart database when exporter work and after, exporter can't detect database status and nothing work.

**Comment by floyd871** [comment]
The exporter always connects and closes the connection after scraping. I could not confirm your issue. After restarting the instance i see the metrics again. Do you have some error messages from the exporter?

**Comment by Seth1u** [comment]
Hello il's good now.
It was librairies problems.
