### ISSUE TITLE
Oracle exporter stop running

### ISSUE THREAD

**Issue by Seth1u** [freenetdigital/prometheus_oracle_exporter#33]
Hello,

I have this problem when i run exporter service.

label value "TNS : l'identificateur de connexion indiqu\xe9 n'a pas pu \xeatre r\xe9solu" is not valid UTF-8
github.com/prometheus/client_golang/prometheus.(*GaugeVec).WithLabelValues(0xc0001400d8, 0xc0003bb7c0, 0x5, 0x5, 0x1006e40, 0x0)
/home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/gauge.go:217 +0xe0
 main.(*Exporter).ScrapeAlertlog(0xc000146100)
 /home/mneumann3/go/src/github.com/freenetgigital/prometheus_oracle_exporter/alertlog.go:138 +0x802
main.(*Exporter).Collect(0xc000146100, 0xc0001ce240)
/home/mneumann3/go/src/github.com/freenetgigital/prometheus_oracle_exporter/main.go:881 +0x2d3
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
/home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:442 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
/home/mneumann3/go/src/github.com/prometheus/client_golang/prometheus/registry.go:453 +0x56e

Can you please tell me if it is exporter problem or my OS service ?

Thanks

**Comment by floyd871** [comment]
Seems that you have some non UTF-8 Chars in the connection string in oracle.conf.

**Comment by Seth1u** [comment]
I have change it but same error.

**Comment by Seth1u** [comment]
And why i can't create my own metrics like :

struct {

rman *prometheus.GaugeVec

rman: prometheus.NewGaugeVec(prometheus.GaugeOpts{
      Namespace: namespace,
      Name:      "rman",
      Help:      "Gauge metric with rman backup",
}, []string{"database","dbinstance","type"}),

and in my function i can add this query for backup 👍 


SELECT OPERATION ,
              STATUS ,
              nvl(replace(OBJECT_TYPE, ' ', '_'),'N/A') ,
                  ROW_LEVEL,
                  TO_CHAR(START_TIME,'YYYY-MM-DD_HH24:MI:SS'),
                  TO_CHAR(END_TIME,'YYYY-MM-DD_HH24:MI:SS')
       FROM V$RMAN_STATUS
       WHERE START_TIME > SYSDATE -1
   ORDER BY START_TIME DESC

Can you tell me why i can't add my own test via main.go ?

I want to contribute for your exporter 
Thanks

**Comment by floyd871** [comment]
Hmm hard to tell.

You have to add your stuff to the functions:
- Describe
- Connect
- Collect

in main.go

**Comment by Seth1u** [comment]
Hello I have already add my stuff to the functions :


type Exporter struct {

  oraversion        *prometheus.GaugeVec

}

  func NewExporter() *Exporter {
    return &Exporter{


    oraversion: prometheus.NewGaugeVec(prometheus.GaugeOpts{
      namespace: namespace,
      Name:      "oraversion",
      Help:      "Gauge metric with Oracle version.",
    }, []string{"database","dbinstance","version"}),



    SrcapeOraversion collects version of oracle 
    func (e *Exporter) ScrapeOraversion() {
      var (
        rows *sql.Rows
        err  error
      )
      for _, conn := range config.Cfgs {
        if conn.db != nil {
          rows, err = conn.db.Query(`select version from v$instance`)
          if err != nil {
            continue
          }
          defer rows.Close()
          for rows.Next() {
            var version string
            if err := rows.Scan(&version); err != nil {
              
            }    
            e.oraversion.WithLabelValues(conn.Database,conn.Instance,"version").Set(version)
          }
        }
      }
    }

func (e *Exporter) Describe(ch chan<- *prometheus.Desc) {


      e.oraversion.Describe(ch)

      }


      func (e *Exporter) Connect() {

      e.oraversion.Reset()
    }


    Collect implements prometheus.Collector.

    e.ScrapeOraversion()
    e.oraversion.Collect(ch)
    



##############
But still not work to get version of oracle.

I try command : go run main.go but get some errors 

Thanks to help
