### ISSUE TITLE
Not able to select multiple column query added in oracle.conf file

### ISSUE THREAD

**Issue by sdpdb** [freenetdigital/prometheus_oracle_exporter#35]
Hi Michael,

This oracle exporter is superb.
But have some complication here , While selecting multiple column in oracle.conf file, then exporter is not able to collect the data.

For Instance,

select name, db_unique_name from gv$database. ---------> This is not work
select count(1) from gv$database. ---------> This working fine.

Can you please help to resolve this issue. Even it is better if we can select multiple column as we wish in query in oracle.conf file.
Looking forward for your response.

**Comment by floyd871** [comment]
You are right. For now Self-Defined Queries supports only ONE Column. 
For now, add a second query.

So this is more a feature request than an issiue,  maybe in the future i will add that.
