### ISSUE TITLE
Start up error: error while loading shared libraries: libclntsh.so.12.1

### ISSUE THREAD

**Issue by anishshaw** [freenetdigital/prometheus_oracle_exporter#37]
Hello, 
I am getting below error when starting the exporter.

[root@seliicbl01060 prometheus]# /root/prometheus/prometheus_oracle_exporter-amd64 -configfile=/root/prometheus/oracle.conf -web.listen-address :9161
/root/prometheus/prometheus_oracle_exporter-amd64: error while loading shared libraries: libclntsh.so.12.1: cannot open shared object file: No such file or directory

System Information:
[oracle@seliicbl01060 dpdump]$ $ORACLE_HOME/OPatch/opatch lsinventory | awk '/^Oracle Database/ {print $NF}'
12.2.0.1.0

Find file from error:
[root@seliicbl01060 prometheus]# find / -name libclntsh\* -ls 2>/dev/null
109193783 7848 -rwxr-x---   1 oracle   dba       8033199 Apr 12  2019 /opt/oracle/product/12gr2/db/inventory/Scripts/ext/lib/libclntshcore.so.12.1
109193786 69960 -rwxr-x---   1 oracle   dba      71638263 Apr 12  2019 /opt/oracle/product/12gr2/db/inventory/Scripts/ext/lib/libclntsh.so.12.1
511713792 7848 -rw-r-----   1 oracle   dba       8033199 Apr 12  2019 /opt/oracle/product/12gr2/db/inventory/backup/2019-04-12_06-58-35PM/Scripts/ext/lib/libclntshcore.so.12.1
511713795 69960 -rw-r-----   1 oracle   dba      71638263 Apr 12  2019 /opt/oracle/product/12gr2/db/inventory/backup/2019-04-12_06-58-35PM/Scripts/ext/lib/libclntsh.so.12.1
251662958    0 lrwxrwxrwx   1 oracle   dba            17 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntsh.so -> libclntsh.so.12.1
251814403 7848 -rwxr-xr-x   1 oracle   dba       8033608 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntshcore.so.12.1
251814406 69964 -rwxr-xr-x   1 oracle   dba      71640160 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntsh.so.12.1
251814408    0 lrwxrwxrwx   1 oracle   dba            12 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntsh.so.10.1 -> libclntsh.so
251814409    0 lrwxrwxrwx   1 oracle   dba            12 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntsh.so.11.1 -> libclntsh.so
251658785    0 lrwxrwxrwx   1 oracle   dba            21 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntshcore.so -> libclntshcore.so.12.1

**Comment by floyd871** [comment]
You have to install oracle-client-software. Normaly you run the exporter on the oracle-server. There are all libaries installed. i've compiled the releases for 12.1.

**Comment by juanrosero** [comment]
I successfully ran the exporter as the oracle user on the server since that user (oracle) already has all the environment variables set. I hope this helps someone with similar problems.
