### ISSUE TITLE
oracledb_query

### ISSUE THREAD

**Issue by octosith** [freenetdigital/prometheus_oracle_exporter#41]
For oracledb_query how do I use queries with multiple values in output?

For example, i'm execute query like this 

`SELECT COUNT(1) FROM object_info oi,cad_qual_dev.v$_onew_request_status v WHERE v.code = oi.status  AND  oi.status IN (004,002)  AND oi.date_registration >= TRUNC(sysdate)  AND oi.address_code  IN ('40.0.0.0','30.0.0.0') AND oi.kind = 2 GROUP BY oi.status, v.name`
with this result
COUNT(1)
7255
582

But, exporter gives only the last result
```
# TYPE oracledb_query gauge
oracledb_query{database="XXX",dbinstance="XXX",name="cnt_pckt_xxx"} 582
```
But, i'm need give all values, and divide them into separate metrics, how can i do this?

Or.  this is a better example

`SELECT oi.status, COUNT(1) FROM object_info oi, cad_qual_dev.v$_onew_request_status v WHERE v.code = oi.status AND oi.date_registration >= trunc(sysdate) AND oi.address_code IN ('40.0.0.0','30.0.0.0') AND oi.kind = 2 GROUP BY oi.status`

And two column in output
STATUS  COUNT(1)
003      	2
004	        7227
002	        307
001	        1921

**Comment by floyd871** [comment]
For now only single values are supported. Tune your query, so that it return only one row.

**Comment by octosith** [comment]
> For now only single values are supported. Tune your query, so that it return only one row.

But if I do, it will be 4 separate DB queries, the main idea why I started using Prometheus is to use one query and then split it into metrics

**Comment by floyd871** [comment]
Supports now Multiple Values and Columns
https://github.com/freenetdigital/prometheus_oracle_exporter/commit/11cabf71ad465b8e9068be30dfdaab8dc7dc57fa
