### ISSUE TITLE
Exporter Crashes on Logfile with non UTF8 Chars

### ISSUE THREAD

**Issue by bastischubert** [freenetdigital/prometheus_oracle_exporter#43]
Hi There,

my exporter is crashing when it's trying to read a logfile which contains "non UTF8" Chars.

INFO[0000] Starting Prometheus Oracle exporter 1.1.3     source="main.go:942"
INFO[0000] Config loaded:  /etc/prometheus-oracle.yml    source="main.go:944"
INFO[0000] Listening on :9161                            source="main.go:952"
panic: label value "Fehler beim autom Ausf\xfchren von Job 128" is not valid UTF-8

goroutine 34 [running]:
github.com/prometheus/client_golang/prometheus.(*GaugeVec).WithLabelValues(0xc000132128, 0xc0002ef360, 0x5, 0x5, 0x100ee40, 0x0)
        /root/go/src/github.com/prometheus/client_golang/prometheus/gauge.go:217 +0xe0
main.(*Exporter).ScrapeAlertlog(0xc000150100)
        /usr/local/prometheus_oracle_exporter11/alertlog.go:145 +0x825
main.(*Exporter).Collect(0xc000150100, 0xc0001405a0)
        /usr/local/prometheus_oracle_exporter11/main.go:879 +0x2c6
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /root/go/src/github.com/prometheus/client_golang/prometheus/registry.go:442 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /root/go/src/github.com/prometheus/client_golang/prometheus/registry.go:534 +0xdf8

from the alert log: 
ORA-12012: Fehler beim autom Ausf<FC>hren von Job 128

i just fixed the log, but you might want to have a look at it if you like ;)

**Comment by floyd871** [comment]
Thanks, Fixed:
https://github.com/freenetdigital/prometheus_oracle_exporter/commit/4d84f80ce204cd60495a5ac212424a47b4b8a960

**Comment by bastischubert** [comment]
awesome! thx @floyd871
