### ISSUE TITLE
SQLNet message from db causes metrics collection to fail. 

### ISSUE THREAD

**Issue by JimKeating** [freenetdigital/prometheus_oracle_exporter#45]
A database I was monitoring returned a "password expiring in 5 days" message to instant client. 
This caused the metrics collection to fail. More seriously, after a couple of hours, the exporter had hundreds of open connection to the database that were not closed as the metrics collection had repeatedly failed. I'm not sure is this a problem with the instant client or the exporter itself, but it is a serious situation if the monitoring tools starts to affect performance of the database itself.
Please advise.

**Comment by floyd871** [comment]
In an older version of the exporter, it didn't close broken connections. But in never versions it releases the old connections firts.
