### ISSUE TITLE
Can't found Oracle errors in grafana dashboard 

### ISSUE THREAD

**Issue by Seth1u** [freenetdigital/prometheus_oracle_exporter#47]
Hello !

Thanks for your new release of prometheus_oracle_exporter with multiples tables query.

I want to know why exporter don't prinf Oracle error like ORA-01089 in alert_instance.log 

Thanks for your reply.

**Comment by floyd871** [comment]
It should work. The rexex for errors is : "O(RA|GG)-[0-9]+" 
Can you post the piece of your altertlog where the error is in? 
With a few lines before and after.

**Comment by Seth1u** [comment]
Hello ! this is errors that exporter can't find.

ORA-12012: error on auto execute of job "SYS"."ORA$AT_OS_OPT_SY_6581"
ORA-01089: immediate shutdown or close in progress - no operations are permitted
ORA-06512: at "SYS.DBMS_STATS", line 43733
ORA-06512: at "SYS.DBMS_STATS", line 44223
ORA-01089: immediate shutdown or close in progress - no operations are permitted
ORA-06512: at "SYS.DBMS_STATS", line 4230
ORA-06512: at "SYS.DBMS_STATS", line 34227
ORA-01089: immediate shutdown or close in progress - no operations are permitted
ORA-06512: at "SYS.DBMS_STATS", line 4230
ORA-06512: at "SYS.DBMS_STATS", line 26099
ORA-01089: immediate shutdown or close in progress - no operations are permitted
ORA-06512: at "SYS.DBMS_STATS", line 44284

Thanks

**Comment by Seth1u** [comment]
When i am do curl  http://localhost:9161/metrics i found error in metrics : 

oracledb_error{code="ORA-01089",database="seven",dbinstance="seven",description="fermeture immdiate en cours - Aucune opration n'est autorise",ignore="1"} 7
oracledb_error{code="ORA-06512",database="database",dbinstance="instance",description=" \"SYS.PRVT_ADVISOR\", ligne 2769",ignore="0"} 11
oracledb_error{code="ORA-1089",database="database",dbinstance="instance",description="aborting process unknown ospid (28092) as a result of ORA-1089",ignore="0"} 22

but in my prometheus server i don't found it !

**Comment by Seth1u** [comment]
OK now
