### ISSUE TITLE
[Question] Drop necessary DBA metrics

### ISSUE THREAD

**Issue by l0rus** [freenetdigital/prometheus_oracle_exporter#48]
Hi @floyd871.
Thanks a lot for your work on exporter.

I have only one question, is there a official way to drop neccesary DBA metrics?
My idea is run clean exporter to scrape self-defined selects **only**.
How to do this?

Best regards, Lorus.

**Comment by floyd871** [comment]
For now it is not suppoted to switch of the internal queries, but  If you want to remove metrics use the drop feature from prometheus with "action" drop.
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_action

**Comment by l0rus** [comment]
@floyd871 Thanks for answer.
I have edited my prometheus config with "action" keep, but its just a gimmic, i.e. exporter still execute selects to DBA views (v$).
Can we have a config with default metrics for editing? (default-metrics.yml for example)
Currently they are hardcoded (as i understand).

**Comment by floyd871** [comment]
https://github.com/freenetdigital/prometheus_oracle_exporter/releases/tag/1.1.5

**Comment by l0rus** [comment]
@floyd871 Thanks a lot.
