### ISSUE TITLE
counter for v$sysstat 

### ISSUE THREAD

**Issue by vt-ms** [freenetdigital/prometheus_oracle_exporter#5]
Thanks for the work on this exporter! I'm just curious if you might consider using a counter metric type for some of these metrics, especially those that come from v$sysstat? My understanding is that the values exposed by that view are always increasing and would thus fit very nicely with Prometheus counter type metric.

**Comment by floyd871** [comment]
You are right, the values from v$sysstat are increasing. But......in a counter metric type you only could "add" the "change" of the value. With the select command i will get the always the absolute values, not the amount of change from the last one.  So the gauge metric type is more handy.

**Comment by vt-ms** [comment]
I think that's part of the benefit of a tool like Prometheus. It handles that kind of calculation for you. For example, you can use the increase function on a counter metric to see how much the value of the metric has increased over a given time range.

https://prometheus.io/docs/concepts/metric_types/#counter
https://prometheus.io/docs/prometheus/latest/querying/functions/#increase()

**Comment by floyd871** [comment]
This doesn't matter.  You can also use increase/irate/rate on a gauge or on a counter metric. I already use that in my dashboards for this exporter.
