### ISSUE TITLE
How to build pormoetheus Oracle exporter 

### ISSUE THREAD

**Issue by ericthoma20** [freenetdigital/prometheus_oracle_exporter#50]
Hello @floyd871 

Thank you for your great job.

Can you tell us or give us your Makefile for build Oracle Prometheus exporter  step by step ? 

It is good job but  if we want to continuous your work, we need the way for compile your exporter.

Sincerely,

**Comment by floyd871** [comment]
Sorry, it is a simple go program refer to: https://golang.org/pkg/go/build/
