### ISSUE TITLE
Checking `asm_disk[group]_stat` instead of or as an alternative to `asm_disk[group[`

### ISSUE THREAD

**Issue by ispringle** [freenetdigital/prometheus_oracle_exporter#51]
asm_disk[group] performs a discovery on each query, this increases overhead on the database. Per Oracle's documentation there is also asm_disk[group]_stat, which is identical to asm_disk[group] but without the discovery overhead: 

> Contains the same columns as V$ASM_DISK, but to reduce overhead, does not perform a discovery when it is queried. V$ASM_DISK_STAT only returns information about any disks that are part of mounted disk groups in the storage system.
> 
> The V$ASM_DISK_STAT view is recommended for monitoring scripts.
> 
> To display information about all disks, use V$ASM_DISK instead. 

> Contains the same columns as V$ASM_DISKGROUP, but to reduce overhead, V$ASM_DISKGROUP_STAT does not perform a discovery when it is queried.
> 
> The V$ASM_DISKGROUP_STAT view is recommended for monitoring scripts.
> 
> To display more complete information about all disks, use V$ASM_DISKGROUP. 

We're wondering if we could get the ASM check updated to query this table instead, as it is the intended table for monitoring.

I wanted to make an issue for this to see if there would be any issues that might arise and if it would be better to change the ASM alert to use these `_stat` tables or maybe to add this as a flag for the installer so that it could be used in lieu of the non-`_stat`. Either way I can get a PR in, just wanted to know which way would be more ideal.

In my opinion, there shouldn't be a reason that everyone can't just use the `_stat` tables instead, that's what these are meant for and this would be a net gain. Additionally it shouldn't cause any breaking change.

**Comment by floyd871** [comment]
You are right.

https://github.com/freenetdigital/prometheus_oracle_exporter/commit/ca6d9f8f574decc4ba60615517654a4bd8a24f02
