### ISSUE TITLE
how to scrape oracledb_recovery metric

### ISSUE THREAD

**Issue by dethu** [freenetdigital/prometheus_oracle_exporter#54]
Hi, first of all thank you for this very useful exporter.

So should i run binary with flag to scrape oracledb_recovery metric
  -recovery
    Expose Recovery percentage usage of FRA (CAN TAKE VERY LONG)
, or just use params in prometheus scrape config ?
Becouse now when i try to scrape this metric I can't do it

```
curl -s 'host:9161/metrics?recovery=true' | grep oracledb_recovery

```
but i can scrape other metrics
```
curl -s 'host:9161/metrics?recovery=true' |grep oracledb_up
# HELP oracledb_up Whether the Oracle server is up.
# TYPE oracledb_up gauge
oracledb_up{database="LWTER.internal",dbinstance="LWTER"} 1
```

**Comment by floyd871** [comment]
It depends on your usecase. If you need the recovery metrics add "recovery=true"..
