### ISSUE TITLE
Custom query doesn't work how described in doc

### ISSUE THREAD

**Issue by alyakimov** [freenetdigital/prometheus_oracle_exporter#65]
Hi! I'm trying to use custom query. I used your example

queries:
    - sql: "select 1 as column1, 'label_value' as column2 from dual"
      name: sample1
      help: "This is my metric number 1"
      metrics:
       - column1
      labels:
       - column2

and in prometheus it shows like this:
oracledb_query{column="COLUMN1",database="DWHSTAGE",dbinstance="DWHSTAGE",name="sample1",row="1"} 1

but I expected something like from your doc. I think "labels" doesn't work correctly. What should I do for getting a correct result?

prometheus_oracle_exporter v1.5
oracle 12.1

**Comment by floyd871** [comment]
Prometheus can only give you 1 value for every colum and row.
 'label_value' it not a column in your db, i think.
so use: 
- sql: "select 1 as column1, 2 as column2 from dual"

You should get:
oracledb_query{column="COLUMN1",database="DWHSTAGE",dbinstance="DWHSTAGE",name="sample1",row="1"} 1
oracledb_query{column="COLUMN2",database="DWHSTAGE",dbinstance="DWHSTAGE",name="sample1",row="1"} 2
