### ISSUE TITLE
document missing the below details

### ISSUE THREAD

**Issue by isshwar** [freenetdigital/prometheus_oracle_exporter#66]
In the usage section of readme, it is said that as below 
-accessfile string
    Last access for parsed Oracle Alerts. (default "access.conf")
-logfile string
    Logfile for parsed Oracle Alerts. (default "exporter.log").

How do i define this? or is this deprecated now? how is this different from config file?

Thanks
Eswar

**Comment by floyd871** [comment]
It is a litte bit missleading. 
"configfile" you can specify the full path + filename of the config.
"accessfile" and "logfile" , you can only specify the filename. It is written in the binary directory....
I will change that in the future,

**Comment by isshwar** [comment]
Hi Thanks but what is this access file and log file?
 
are we speaking about the oracle access and log files? 

In the config file, we will give all the details required to connect to the database. 

also, the current exporter , can it report on rman backups? i have oracle rman running and could not find from the document if it could report on rman back ups?

Thanks
Eswar

**Comment by floyd871** [comment]
No, Logfile and Acceslog from the exporter. Debugging purposes.
