### ISSUE TITLE
tried running the exporter on oracle vm but getting the attached error message

### ISSUE THREAD

**Issue by isshwar** [freenetdigital/prometheus_oracle_exporter#67]
Hi,

I have tried running the exporter on oracle vm and my oracle is running version 11.1. this is failing with the below error message. any idea on how to bypass this?

./prometheus_oracle_exporter-amd64: error while loading shared libraries: libclntsh.so.12.1: cannot open shared object file: No such file or directory

**Comment by floyd871** [comment]
Binaries are compiled for Oracle 12.1 client.
Compile it yourself with 11.1 client or install the 12.1 client on your machine.
