### ISSUE TITLE
oracledb_alert metric are not working

### ISSUE THREAD

**Issue by sangrhee88** [freenetdigital/prometheus_oracle_exporter#70]
Hello, out of box oracledb_alert alert metrics are not working.

1. Alert.log shows ORA- error
ORA-07445: SIMULATED ERROR, JUST FOR TESTING, IGNORE!!!
2020-07-24T21:53:46.638049+00:00
ORA-07445: SIMULATED ERROR, JUST FOR TESTING, IGNORE!!!

2. cat oracle.conf has correct alert.log path
connections:
 - connection: user/password@tnaname
   database: xxxx
   instance: xxxx
   alertlog:
    - file: /axxx/trace/alert_dbname.log

3. The process is up and running as ==>
prometheus_oracle_exporter -configfile=/tmp/oracle.conf -web.listen-address 0.0.0.0:9500 -defaultmetrics -recovery

4. curl -s http://x.x.x.x:9500/metrics | grep oracledb_error
show no data

**Comment by sangrhee88** [comment]
Found the root cause. The timestamp format was changed on 12.2 and onward
Revert the Oracle's timestamp to the original.
alter system set UNIFORM_LOG_TIMESTAMP_FORMAT=FALSE scope=both;
or
fix the layout on this code.
var (
	Errors    []oraerr
	oralayout = "Mon Jan 02 15:04:05 2006"

**Comment by Seth1u** [comment]
Hello! Are you tested after your change in alertlog.go? because i have a same problem and it not work after compilation of exporter?

**Comment by sangrhee88** [comment]
Yea, change the Oracle timestamp to "alter system set UNIFORM_LOG_TIMESTAMP_FORMAT=FALSE scope=both;"
Then should work.

**Comment by Seth1u** [comment]
oracledb_exporter_last_scrape_error{instance="lab", job="oracle-short"} value 0. But i have some errors in alert_SID.log file. I have compiled exporter to 19.3 oracle version

**Comment by sangrhee88** [comment]
check curl -s http://your IP:port/metrics | grep oracledb_error to see if the client has error. 
The output should be something like this ==> oracledb_error{code="ORA-0600",database="orcl",dbinstance="orcl1",description="SIMULATED ERROR, ORCL1, IGNORE!!!",ignore="0"}
I validated it with 19.3 Oracle version, It works for RAC and single node.

**Comment by Seth1u** [comment]
Ok! May be I have not compiled all files of the exporter correctly... Did you have any mail or discord channel for exchange? I have developed news functions in this exporter and we can discuss on it if you want. Thanks

**Comment by sangrhee88** [comment]
I am not an owner of this repo. So you should contact with the repo owner for any contributions.
To build it, you might need to run something like this.

export GOPATH=/home/oracle/go
go get -u github.com/freenetdigital/prometheus_oracle_exporter
cd /home/oracle/go/src/github.com/freenetdigital/prometheus_oracle_exporter/
go install
go build

**Comment by This-is-me-now** [comment]
Fixed it for me by replacing 

`oralayout = "Mon Jan 02 15:04:05 2006"`

with

`oralayout = "2006-01-02T15:04:05.000000+00:00"`

https://github.com/freenetdigital/prometheus_oracle_exporter/blob/ca6d9f8f574decc4ba60615517654a4bd8a24f02/alertlog.go#L37

Compiled the latest code with this change with `go build` and it works for me now. :)

Further information about the format change: 
https://mikedietrichde.com/2017/05/30/alert-log-new-timestamp-format-oracle-12-2/
