### ISSUE TITLE
Missing columns in output

### ISSUE THREAD

**Issue by adiithyan** [freenetdigital/prometheus_oracle_exporter#71]
Hello,

First of all, many thanks for creating a great oracle exporter. It is really cool. 
I am facing the following problem while fetching data from v$sqlstats. I noticed that one column is not being returned in the output in prometheus. My config file is as follows for the query that I am running; (Everything except QUERY_ID is generated)

    - sql: "select sql_id as QUERY_ID, parse_calls as PARSE_CALLS, BUFFER_GETS as BUFFER_GETS, rows_processed as ROWS_PROCESSED , executions as EXECUTIONS, ELAPSED_TIME as ELAPSED_TIME, AVG_HARD_PARSE_TIME as AVG_HARD_PARSE_TIME from V$SQLSTATS"
      name: Query_Metrics
      metrics:
       - QUERY_ID
       - PARSE_CALLS
       - BUFFER_GETS
       - ROWS_PROCESSED
       - EXECUTIONS
       - ELAPSED_TIME
       - AVG_HARD_PARSE_TIME

**Comment by adiithyan** [comment]
Found out that this is because sql_id is VARCHAR2. Looks like currently VARCHAR2 data types aren't supported. Please do let me know if otherwise.

**Comment by ChSanjayBabu** [comment]
hey @adiithyan can you check #72  and see if u have any idea

**Comment by floyd871** [comment]
This is by design.
Prometheus only support numeric values as metrics. sql_id is CHAR (VARCHAR).
