### ISSUE TITLE
Add possibility to filter by instance in grafana ?

### ISSUE THREAD

**Issue by zrcorsica** [freenetdigital/prometheus_oracle_exporter#9]
Hi,

I have two oracle database with same SID (there are clones but hosted on different servers) and in Grafana dashboard I can't differenciate databases.

Please, Is it possible to add a new tab for filter by instance ? (actualy there are only filters for database and dbinstance)

thank you.

**Comment by floyd871** [comment]
Just add in Grafana a Dropdownbox for the Host (Variables) and add the variable in all Dashbords.
